<?php namespace MLM;
// via 
// http://daylerees.com/trick-validation-within-models
// http://driesvints.com/blog/using-laravel-4-model-events
// 

class BaseModel extends \Eloquent
{
    public static function boot()
    {
        parent::boot();

        static::creating(function($model)
        {
            // attempt validation
            return ($model->validate());
        });

        static::updating(function($post)
        {
            
        });
    }

    /**
     * Validation Rules
     * 
     * @var array
     */
    protected $rules = array();

    /**
     * Store errors generated by the validator
     * 
     * @var array
     */
    private $errors;

    /**
     * Custom Error messages
     * @var array
     */
    private $messages = array();

    /**
     * Attempt to validate the provided data
     * 
     * @param  [type] $data [description]
     * @return [type]       [description]
     */
    public function validate()
    {
        // make a new validator object
        $v = \Validator::make($this->getAttributes(), $this->rules);

        // check for failure
        if ($v->fails())
        {
            // set errors and return false
            $this->errors = $v->messages();
            return false;
        }

        // validation passes
        return true;
    }

    /**
     * Return the Validation Errors
     * @return array 
     */
    public function errors()
    {
        return $this->errors;
    }
}