<?php namespace MLM;
// via http://daylerees.com/trick-validation-within-models

class BaseModel extends \Eloquent
{
    /**
     * Custom Error messages
     * @var array
     */
    private $messages = array();

    /**
     * Store errors generated by the validator
     * 
     * @var array
     */
    private $errors;

    /**
     * Validation Rules
     * 
     * @var array
     */
    protected $rules = array();

    /**
     * Attempt to validate the provided data
     * 
     * @param  [type] $data [description]
     * @return [type]       [description]
     */
    public function validate($data)
    {
        // make a new validator object
        $v = Validator::make($data, $this->rules);

        // check for failure
        if ($v->fails())
        {
            // set errors and return false
            $this->errors = $v->errors;
            return false;
        }

        // validation pass
        return true;
    }

    /**
     * Return the Validation Errors
     * @return array 
     */
    public function errors()
    {
        return $this->errors;
    }
}